title = "Studying and Developing Distributed Barrier Algorithms Using The Hybrid Programming Model Combining MPI-3 and C++11"
institution = "Vietnam National University - Ho Chi Minh City University of Technology"
semester = 241
major = "Computer Science"
faculty = "Computer Science and Engineer"

[course]
name = "Specialized Project"
id = "CO4029"

[[committee]]
id = 12
secretary = "Nguyễn Quang Hùng"

[[teachers]] 
name = "Thoại Nam" 
[[teachers]] 
name = "Diệp Thanh Đăng"

[[students]]
name = "Phạm Võ Quang Minh"
id = 2111762

[fonts]
serif = "Times New Roman"
monospace = "JetBrains Mono"
